#se uma aplicação quiser se conectar ao servidor de autorização
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080

spring:
  application:
    name: libraryapi
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
  flyway:
    baseline-on-migrate: true

  springdoc:
    override-with-generic-response: false