DO $$
BEGIN
	RAISE NOTICE 'INITIALIZING MIGRATION FOR EMAIL COLUMN';

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'usuario' AND column_name = 'email'
    ) THEN
		RAISE NOTICE 'EMAIL COLUMN DOES NOT EXIST, CREATING...';

		ALTER TABLE usuario
		ADD COLUMN email VARCHAR(100);

		UPDATE usuario
		SET email = 'NECESSARIOATUALIZAR@TESTE.COM'
		WHERE email IS NULL;

		ALTER TABLE usuario
		ALTER COLUMN email SET NOT NULL;

		RAISE NOTICE 'EMAIL COLUMN ADDED TO USUARIO TABLE SUCCESSFULLY';
	ELSE
		RAISE NOTICE 'EMAIL COLUMN ALREADY EXISTS.';
	END IF;
END;
$$
