DO $$
BEGIN
	RAISE NOTICE 'INICIANDO MIGRAÇÃO QUE VALIDA EMAIL';

    IF NOT EXISTS
        (        SELECT 1 FROM information_schema.columns
                 WHERE table_name='usuario' AND column_name='email') THEN
		RAISE NOTICE 'COLUNA EMAIL NAO EXISTIA, ADICIONANDO...';
		ALTER TABLE USUARIO
		ADD COLUMN EMAIL VARCHAR(100);

		UPDATE USUARIO
		SET
		EMAIL = 'NECESSARIOATUALIZAR@TESTE.COM'
		WHERE
		EMAIL IS NULL;

		ALTER TABLE USUARIO
		ALTER COLUMN EMAIL
		SET NOT NULL;
		RAISE NOTICE 'COLUNA EMAIL ADICiONADA COM SUCESSO';
	ELSE
		RAISE NOTICE 'COLUNA EMAIL JA EXISTIA.';
	END IF;
END;
$$