DO $$
BEGIN
	RAISE NOTICE 'INITIALIZING CLIENT TABLE MIGRATION';

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'client'
    ) THEN
		RAISE NOTICE 'CLIENT TABLE DOES NOT EXIST...';
		RAISE NOTICE 'CREATING TABLE';

		CREATE TABLE client (
		    id uuid NOT NULL PRIMARY KEY,
		    client_id VARCHAR(150) NOT NULL,
		    client_secret VARCHAR(400) NOT NULL,
		    redirect_uri VARCHAR(200) NOT NULL,
		    scope VARCHAR(50)
		);

		RAISE NOTICE 'ALL GOOD, CLIENT TABLE CREATED SUCCESSFULLY';
	ELSE
		RAISE NOTICE 'CLIENT TABLE ALREADY EXISTS.';
	END IF;
END;
$$
